### ISSUE TITLE
Needs a LICENSE

### ISSUE THREAD

**Issue by keyan** [pallets/flask-ext-migrate#2]
Needs to have a license added. Not sure if there is an expectation for what license to use for pocoo projects.

**Comment by untitaker** [comment]
Should be new (3-clause) BSD or MIT. I'd root for MIT.

On 5 September 2015 01:59:39 CEST, Keyan Pishdadian notifications@github.com wrote:

> Needs to have a license added. Not sure if there is an expectation for
> what license to use for pocoo projects.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/pocoo/flask-ext-migrate/issues/2

## 

Sent from my phone. Please excuse my brevity.

**Comment by jeffwidman** [comment]
@keyan any chance of adding a license? BSD or MIT is fine with me

**Comment by RonnyPfannschmidt** [comment]
as per setup.py its already BSD, can someone add a pr perhaps?
