### ISSUE TITLE
Unnecessary import aliasing after migration 

### ISSUE THREAD

**Issue by ye** [pallets/flask-ext-migrate#23]
See below, the `abort` method was unnecessarily aliased to the same identifier of itself.  `from flask_restful import abort` would have been suffice. 

```bash
$ flask_ext_migrate api/views/forum.py
$ git diff 
diff --git a/api/views/forum.py b/api/views/forum.py
index bdc9803..065f7ac 100644
--- a/api/views/forum.py
+++ b/api/views/forum.py
@@ -1,5 +1,5 @@
 from flask import request
-from flask.ext.restful import abort
+from flask_restful import abort as abort
```

**Comment by keyan** [comment]
Hi @ye, thanks for opening this issue!

So I'm a bit surprised to see this as this issue should have been resolved by @GregoryVigoTorres's PR https://github.com/pallets/flask-ext-migrate/pull/11. Can you confirm what version of `flask-ext-migrate` you have installed? Also, I just pushed a new release, could you test if upgrading resolves this bug for you?

**Comment by ye** [comment]
@keyan the version I installed was `0.1.0`. And yes, you were right that after a `pip install -U flask_ext_migrate`, the new version `1.0.0` does seem to resolve the unnecessary aliasing issue.

Thanks and I am closing this as it's no longer the case in latest version.

**Comment by keyan** [comment]
Great! Happy to hear it 😄 

Thanks again for submitting this and for using the package.
